apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: aws-actions-connector
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-aws-iam
    version: ">=v2"
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: Sets up GitHub Actions OIDC federation with AWS for secure CI/CD access
    without long-lived credentials.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # aws-actions-connector

    Sets up GitHub Actions OIDC federation with AWS, creating the OIDC provider, IAM role, and policy attachment for secure CI/CD access.
  repository: ghcr.io/hops-ops/aws-actions-connector
  source: github.com/hops-ops/aws-actions-connector
