# Import existing GitHub Actions OIDC resources
# Use this example when you have pre-existing OIDC provider, role, and policy attachment
# that you want Crossplane to manage.
#
# Set managementPolicies to exclude Delete to prevent accidental deletion of the imported resources.
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: ActionsConnector
metadata:
  name: imported-gha
  namespace: default
spec:
  accountId: "123456789012"
  providerConfigRef:
    name: default
    kind: ProviderConfig
  # Exclude Delete from management policies to prevent accidental deletion
  managementPolicies:
  - Create
  - Update
  - Observe
  - LateInitialize
  github:
    owner: my-org
    repository: "*"
    refPattern: "*"
  # External names of existing AWS resources to import
  imports:
    oidcProvider: arn:aws:iam::123456789012:oidc-provider/token.actions.githubusercontent.com
    role: existing-gha-role
    policyAttachment: existing-gha-role/arn:aws:iam::aws:policy/AdministratorAccess
  # Role configuration (name must match imported role)
  role:
    name: existing-gha-role
  policy:
    arn: arn:aws:iam::aws:policy/AdministratorAccess
  tags:
    imported: "true"
    managed-by: crossplane
